# site settings
title: Mitchell
subtitle: Moore
email: 
description: Porfolio and Biographic Information for your convenience.
#baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author: Mitchell Moore
street_address: 
city: Alabaster
state: AL
zip_code: 35007
country: United States of America
phone: (256) 613-1484

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/MMoore97/
github_url: https://github.com/mmoo97 
gitlab_url: https://gitlab.rc.uab.edu/mmoo97 
googleplus_url:
instagram_url: https://www.instagram.com/moore_money_moore_problems/
linkedin_url: https://www.linkedin.com/in/mitchell-moore-037162161/ 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
